# Generated by Django 4.2.5 on 2023-09-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='created_date',
        ),
    ]
