# Generated by Django 4.2.5 on 2023-09-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
